name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Build iOS app
        run: |
          set -o pipefail
          xcodebuild \
            -scheme ReverseDynamic \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            SWIFT_OPTIMIZATION_LEVEL=-O \
            SWIFT_COMPILATION_MODE=wholemodule \
            ENABLE_PREVIEWS=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            clean build | xcpretty --color
