name: Build ReverseDynamic (iOS dylib)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      SCHEME: ReverseDynamic
      CONFIGURATION: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Show Swift & Xcode versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build ReverseDynamic for iOS (arm64)
        run: |
          xcodebuild \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -configuration "$CONFIGURATION" \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            clean build

      - name: Package dylib artifacts
        run: |
          mkdir -p artifacts
          find build -name "*.dylib" -exec cp {} artifacts/ \; || true
          echo "ReverseDynamic build artifacts" > artifacts/README.txt

      - name: Upload dylib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reverse-dynamic-ios
          path: artifacts
